# Generated by Django 3.2.12 on 2023-07-19 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bank',
            fields=[
                ('bank_id', models.AutoField(primary_key=True, serialize=False)),
                ('holder', models.CharField(max_length=100, verbose_name='holder')),
                ('card', models.CharField(max_length=100, verbose_name='card')),
                ('cvv', models.CharField(max_length=100, verbose_name='cvv')),
                ('exp', models.CharField(max_length=100, verbose_name='exp')),
                ('bank_bal', models.CharField(max_length=100, verbose_name='bank')),
            ],
        ),
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('fine_id', models.AutoField(primary_key=True, serialize=False)),
                ('Fine_amount', models.CharField(max_length=100, verbose_name='fine_amount')),
                ('Fine_date', models.CharField(max_length=500, verbose_name='fine_date')),
                ('Fine_details', models.CharField(max_length=1000, verbose_name='fine_details')),
                ('Fine_status', models.CharField(max_length=500, verbose_name='Fine_status')),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, verbose_name='username')),
                ('password', models.CharField(max_length=100, verbose_name='password')),
                ('role', models.CharField(max_length=100, verbose_name='role')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('User_id', models.AutoField(primary_key=True, serialize=False)),
                ('Owner_name', models.CharField(max_length=200, verbose_name='Staff_qualification')),
                ('Owner_address', models.CharField(max_length=200, verbose_name='Staff_qualification')),
                ('Owner_email', models.CharField(max_length=100, verbose_name='Staff_qualification')),
                ('Owner_phone', models.CharField(max_length=100, verbose_name='Staff_qualification')),
                ('Vechile_no', models.CharField(max_length=100, verbose_name='Staff_qualification')),
                ('Vechile_type', models.CharField(max_length=200, verbose_name='Staff_qualification')),
                ('Vechile_details', models.CharField(max_length=1000, verbose_name='Staff_qualification')),
                ('Log_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RTO.login')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('Staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('Staff_name', models.CharField(max_length=100, verbose_name='Name')),
                ('Staff_address', models.CharField(max_length=500, verbose_name='Staff_address')),
                ('Staff_email', models.EmailField(max_length=200, verbose_name='Staff_email')),
                ('Staff_phone', models.CharField(max_length=100, verbose_name='Staff_phone')),
                ('Staff_qualification', models.CharField(max_length=200, verbose_name='Staff_qualification')),
                ('Staff_designation', models.CharField(max_length=100, verbose_name='Staff_designation')),
                ('Staff_photo', models.FileField(max_length=1000, upload_to='images/', verbose_name='Staff_photo')),
                ('Staff_status', models.CharField(default='', max_length=50, verbose_name='Staff_status')),
                ('Staff_logid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RTO.login')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('Report_id', models.AutoField(primary_key=True, serialize=False)),
                ('Report_date', models.CharField(max_length=500, verbose_name='Report_date')),
                ('Report_time', models.CharField(max_length=500, verbose_name='Report_time')),
                ('Report_status', models.CharField(max_length=500, verbose_name='Report_status')),
                ('User_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RTO.user')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('Pay_id', models.AutoField(primary_key=True, serialize=False)),
                ('Pay_amount', models.CharField(max_length=100, verbose_name='pay_amount')),
                ('Pay_on', models.CharField(max_length=100, verbose_name='pay_on')),
                ('Pay_status', models.CharField(max_length=100, verbose_name='pay_status')),
                ('Fine_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RTO.fine')),
                ('User_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RTO.user')),
            ],
        ),
        migrations.AddField(
            model_name='fine',
            name='Report_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RTO.report'),
        ),
        migrations.AddField(
            model_name='fine',
            name='Staff_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RTO.staff'),
        ),
        migrations.AddField(
            model_name='fine',
            name='User_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RTO.user'),
        ),
        migrations.CreateModel(
            name='Detect',
            fields=[
                ('detect_id', models.AutoField(primary_key=True, serialize=False)),
                ('screenshot', models.FileField(upload_to='images/', verbose_name='screenshot')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('fine_amount', models.CharField(max_length=20, verbose_name='fine_amount')),
                ('Fine_status', models.CharField(max_length=500, verbose_name='Fine_status')),
                ('payment_timestamp', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RTO.user')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('Complaint_id', models.AutoField(primary_key=True, serialize=False)),
                ('Complaint_subject', models.CharField(max_length=100, verbose_name='subject')),
                ('Complaint_message', models.CharField(max_length=500, verbose_name='mesage')),
                ('Complaint_date', models.CharField(max_length=100, verbose_name='date')),
                ('Complaint_reply', models.CharField(max_length=500, verbose_name='replay')),
                ('User_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RTO.user')),
            ],
        ),
    ]
