# Generated by Django 4.0.3 on 2023-07-21 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RTO', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detect',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
